version: "3"
services:

  redis:
    image: redis:alpine
    container_name: tm-master-data-redis
    
  webserver:
    image: nginx:alpine
    container_name: tm-master-data-webserver
    working_dir: /application
    volumes:
        - .:/application
        - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8088:80"

  php-fpm:
    build: ./docker/php-fpm
    container_name: tm-master-data-php-fpm
    working_dir: /application
    volumes:
      - .:/application
      - ./docker/php-fpm/php-ini-overrides.ini:/etc/php/7.2/fpm/conf.d/99-overrides.ini
  
  mysql:
    image: mysql:5.6
    container_name: tm-master-data-mysql
    working_dir: /application
    volumes:
      - .:/application
    environment:
      - MYSQL_ROOT_PASSWORD=sroot
      - MYSQL_DATABASE=dbapps
      - MYSQL_USER=eprocdb
      - MYSQL_PASSWORD=sroot
    ports:
      - "8090:3306"
  